module.exports = {
    ACCESS_TOKEN_LIFE: '15m',
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET || '612f7d403c644993af60d1deacc',
    AWS_S3_ACCESS_KEY: process.env.AWS_S3_ACCESS_KEY,
    AWS_S3_NAME: process.env.AWS_S3_NAME,
    AWS_S3_REGION: process.env.AWS_S3_REGION,
    AWS_S3_SECRET_KEY: process.env.AWS_S3_SECRET_KEY,
    CONFIRM_TOKEN_SECRET: process.env.CONFIRM_TOKEN_SECRET || '613asdas67fab0df72e86f8028c76',
    CONFIRM_TOKEN_LIFE: '2h',
    EMAIL_BROADCAST: process.env.EMAIL_BROADCAST || 'test@email.com',
    EMAIL_BROADCAST_PASS: process.env.EMAIL_BROADCAST_PASS || '12345',
    FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:5000/',
    MONGO_URL: process.env.MONGO_URL || 'mongodb://localhost:27017/usersDbInoxoft',
    PORT: process.env.PORT || 5000,
    REFRESH_TOKEN_LIFE: '31d',
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || '612f8e91ef4212bcf103c29bref',
    RESET_TOKEN_LIFE: '2h',
    RESET_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || '2bcf103c29bref612f8e91ef421',
    SUPER_ADMIN_AGE: process.env.SUPER_ADMIN_AGE,
    SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
    SUPER_ADMIN_NAME: process.env.SUPER_ADMIN_NAME,
    SUPER_ADMIN_PASSWORD: process.env.SUPER_ADMIN_PASSWORD,
};
