module.exports = {
    _ID: '_id',
    ACCOUNT_CREATED: 'Your account successfully created! Thanks for signing up.',
    ACCOUNT_CONFIRMED: 'Your account successfully confirmed! Go to login page.',
    BODY: 'body',
    EMAIL: 'email',
    EMAIL_ALREADY_EXIST:
    'This email already exists. Please check your email and try again. Or login.',
    ENTITY_EXIST: 'Entity is already exists',
    ENTITY_NOT_FOUND: 'Entity not found',
    FAIL_MONGO: 'Failed connection to MongoDb: ',
    FAIL_CREATE_SUPER_ADMIN: 'Fail create super admin',
    FILE_TOO_BIG: 'file is too big',
    INVALID_AGE: 'Invalid age. Must be from 6 to 110. Please check your age and try again.',
    INVALID_CONTENT: 'Invalid content. Please check your content and try again.',
    INVALID_EMAIL: 'Invalid email. Please check your email and try again.',
    INVALID_ID: 'Invalid id. There is no user with this id.',
    INVALID_NAME: 'Invalid name. Please check your name and try again.',
    INVALID_PASSWORD:
    // eslint-disable-next-line max-len
    'Invalid password. Must have at least 6 characters, one digit and a capital letter. Please check your password and try again.',
    INVALID_TITLE: 'Invalid title. Please check your title and try again.',
    INVALID_TOKEN: 'Invalid token',
    NO_REPLY: 'No reply',
    NOT_CONFIRMED: 'Your account is not confirmed. Please, check your email and confirm account',
    PAGE_NOT_FOUND: 'Page not found.',
    PARAMS: 'params',
    PASSWORD_CHANGED: 'Your password was successfully changed',
    POST_ID: 'post_id',
    POST_NOT_FOUND: 'Post not found.',
    QUERY: 'query',
    REQUIRED_AGE: 'Age is required.',
    REQUIRED_EMAIL: 'Email is required.',
    REQUIRED_NAME: 'Name is required.',
    REQUIRED_PASSWORD: 'Password is required.',
    SERVER_RUNNING: '🚀 Server running on port:',
    SEND_RESET_TOKEN: 'To reset your password please, check your email',
    SOME_WRONG: 'Oops, something went wrong. Please, contact our technical support team.',
    SUPER_ADMIN_CREATED: 'Super admin successfully created',
    SUPER_ADMIN_UNDEFINED: 'Super admin credentials is not defined. Check variables in your .env file',
    USER: 'user',
    USER_ID: 'user_id',
    USER_NOT_FOUND: 'User not found.',
    WRONG_ACCESS: 'You do not have access',
    WRONG_CREDENTIALS: 'Invalid credentials',
    WRONG_DATA: 'Wrong data.',
    WRONG_FILE_FORMAT: 'Wrong file format',
    WRONG_LOGIN:
    'Invalid credentials. Please check your email, password and try again. Or register.',
    WRONG_POST: 'Invalid data. Please check your post title, content and try again.',
    WRONG_SIGNUP:
    'Invalid credentials. Please check your name, age, email, password and try again.',
    WRONG_TEMPLATE: 'Wrong template variables',
    WRONG_UPDATE_USER:
    'Invalid credentials. Please check your name, age, email and try again.'
};
